# Header
menu:
  About: http://ashaimpact.com/#about
  Team: http://ashaimpact.com/#team
  Initiatives: http://ashaimpact.com/#initiatives
  Contact: http://ashaimpact.com/#contact
  Blog: /blog-page
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: